-- Creating the tables
--  Table 1: VACANT_JOBS
CREATE TABLE vacant_jobs (
  job_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name     VARCHAR2(150) NOT NULL,
  description  VARCHAR2(4000),
  posted_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  expires_at   TIMESTAMP NOT NULL,
  isActive     CHAR(1) DEFAULT 'Y' NOT NULL
    CONSTRAINT ck_vacant_jobs_isactive CHECK (isActive IN ('Y','N'))
);


-- Table 2: NOTIFICATIONS
CREATE TABLE notifications (
  notification_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type                 VARCHAR2(20) NOT NULL
    CONSTRAINT ck_notification_type CHECK (type IN ('new post','update','application')),
  message              VARCHAR2(4000) NOT NULL,
  created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  number_of_applicants NUMBER DEFAULT NULL,
  job_id               NUMBER NOT NULL,
    CONSTRAINT fk_notification_job FOREIGN KEY (job_id) REFERENCES vacant_jobs (job_id)
);


-- Table 3: JOB_APPLICATIONS
CREATE TABLE job_applications (
  application_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_email VARCHAR2(255) NOT NULL,
  applied_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  job_id          NUMBER NOT NULL,
    CONSTRAINT fk_application_job FOREIGN KEY (job_id) REFERENCES vacant_jobs (job_id)
);


-- Table 4: JOBS_POSTING_ARCHIVE
CREATE TABLE jobs_posting_archive (
  job_id       NUMBER PRIMARY KEY,
  job_name     VARCHAR2(150) NOT NULL,
  description  VARCHAR2(4000),
  posted_at    TIMESTAMP NOT NULL,
  expires_at   TIMESTAMP NOT NULL
);

-- ===========================================================================
-- Part A
-- new job posting procedure
CREATE OR REPLACE PROCEDURE new_post_notification (p_job_id IN NUMBER, p_job_name IN VARCHAR2, p_description IN VARCHAR2)
AS
BEGIN
INSERT INTO notifications (type, message, job_id) VALUES ('new post', '[' || p_job_name || '] ' || p_description, p_job_id);
END new_post_notification;
/

-- TRIGGER TO START THE register_notification_trigger PROCEDURE ON INSERTION
CREATE OR REPLACE TRIGGER register_notification_trigger
AFTER INSERT ON vacant_jobs
FOR EACH ROW
BEGIN
  new_post_notification(:NEW.job_id, :NEW.job_name, :NEW.description);
END register_notification_trigger;
/

-- testing
INSERT INTO vacant_jobs (job_name, description, expires_at) VALUES ('Backend Developer', 'Build APIs in Spring Boot', SYSTIMESTAMP + 3);
INSERT INTO vacant_jobs (job_name, description, expires_at) VALUES ('DevOps Engineer', 'Manage CI/CD pipelines and cloud infrastructure', SYSTIMESTAMP + 5);
SELECT * FROM VACANT_JOBS;
SELECT * FROM NOTIFICATIONS;

-- ===========================================================================
-- Part B
-- function to convert job description to lower case (custom)
CREATE OR REPLACE FUNCTION to_lowercase (p_text IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
-- 'translate' replaces every character from the top to the corresponding character at the bottom
RETURN TRANSLATE(p_text,
                 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
                 'abcdefghijklmnopqrstuvwxyz');
END to_lowercase;
/

-- procedure to insert a new update record in the notifications table
CREATE OR REPLACE PROCEDURE update_notification (p_job_id IN NUMBER, p_job_name IN VARCHAR2,p_description IN VARCHAR2)
AS
BEGIN
INSERT INTO notifications (type, message, job_id)
VALUES ('update', '[' || p_job_name || '] ' || p_description, p_job_id);
END update_notification;
/

-- creating a trigger to change the description from upper case to lower case
CREATE OR REPLACE TRIGGER vacant_jobs_description_update_trigger
BEFORE UPDATE OF description ON vacant_jobs -- before is used here since we are modifying and 'after' is used for reading only
    FOR EACH ROW
BEGIN
  :NEW.description := to_lowercase(:NEW.description);
END vacant_jobs_description_update_trigger;
/

-- implement the changes in the notifications table
CREATE OR REPLACE TRIGGER notifications_update_trigger
AFTER UPDATE OF description ON vacant_jobs
    FOR EACH ROW
BEGIN
  update_notification(:OLD.job_id, :NEW.job_name, :NEW.description);
END notifications_update_trigger;
/

-- testing
UPDATE vacant_jobs SET DESCRIPTION = 'MANAGE CI/CD PIPELINES AND CLOUD INFRASTRUCTURE' WHERE job_name = 'DevOps Engineer';
SELECT * FROM VACANT_JOBS;
SELECT * FROM NOTIFICATIONS;


-- ===========================================================================
-- Part C
-- procedure to add all the records in vacant_jobs table to jobs_posting_archive table
CREATE OR REPLACE PROCEDURE archive_vacant_jobs AS
BEGIN
INSERT INTO jobs_posting_archive (job_id, job_name, description, posted_at, expires_at)
SELECT job_id, job_name, description, posted_at, expires_at FROM vacant_jobs
                                                                     MINUS
SELECT job_id, job_name, description, posted_at, expires_at FROM jobs_posting_archive;

COMMIT;
END archive_vacant_jobs;
/

-- procedure to delete jobs from vacant_jobs table if they become inactive
CREATE OR REPLACE PROCEDURE REMOVE_INACTIVE_JOBS AS
BEGIN
DELETE FROM vacant_jobs WHERE isActive = 'N';
COMMIT;
END REMOVE_INACTIVE_JOBS;
/

--procedure to check if the job is active or not and set isActive to N if not
CREATE OR REPLACE PROCEDURE check_job_is_active AS
BEGIN
UPDATE vacant_jobs SET isActive = 'N' WHERE expires_at <= systimestamp AND isActive = 'Y';
COMMIT;
END check_job_is_active;
/

-- JOB TO FIRST CHECK IF JOB IS ACTIVE
BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME        => 'EXPIRY_WATCH_JOB',
    JOB_TYPE        => 'PLSQL_BLOCK',
    JOB_ACTION      => 'BEGIN check_job_is_active; END;',
    REPEAT_INTERVAL => 'FREQ=MINUTELY; INTERVAL=1',
    START_DATE      => systimestamp,
    ENABLED         => TRUE
  );
END;
/

--PROCEDURE TO ADD TO THE ARCHIVE TABLE AND DELETE FROM VACANT_JOBS TABLE
CREATE OR REPLACE PROCEDURE archive_and_clear_board AS
BEGIN
  archive_vacant_jobs;
  REMOVE_INACTIVE_JOBS;
END archive_and_clear_board;
/

BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME        => 'ARCHIVE_AND_CLEAR_JOB',
    JOB_TYPE        => 'PLSQL_BLOCK',
    JOB_ACTION      => 'BEGIN archive_and_clear_board; END;',
    REPEAT_INTERVAL => 'FREQ=MINUTELY; INTERVAL=1',
    START_DATE      => systimestamp,
    ENABLED         => TRUE
  );
END;
/

-- testing
SELECT * FROM JOBS_POSTING_ARCHIVE;
INSERT INTO vacant_jobs (job_name, description, expires_at, isActive) VALUES ('QA Tester', 'Verify the archive and purge flow works correctly', SYSTIMESTAMP + 1/1440, 'Y');
COMMIT;
SELECT * FROM VACANT_JOBS;

-- fixing "ORA-02292: integrity constraint (SYSTEM.FK_NOTIFICATION_JOB) violated - child record found error
-- DROPPING THE CONSTRAINTS SO THAT THEY POINT TO THE JOBS_POSTING_ARCHIVE TABLE TO AVOID FK CONTRAINT ERROR
ALTER TABLE job_applications DROP CONSTRAINT fk_application_job;
ALTER TABLE notifications    DROP CONSTRAINT fk_notification_job;

ALTER TABLE job_applications
    ADD CONSTRAINT fk_application_job_arch
        FOREIGN KEY (job_id) REFERENCES jobs_posting_archive (job_id);

ALTER TABLE notifications
    ADD CONSTRAINT fk_notification_job_arch
        FOREIGN KEY (job_id) REFERENCES jobs_posting_archive (job_id);


-- CREATING A TRIGGER SO THAT THE RECORD EXISTS IN THE JOBS_POSTING_ARCHIVE TABLE
CREATE OR REPLACE TRIGGER trg_vacant_jobs_archive
AFTER INSERT ON vacant_jobs
FOR EACH ROW
BEGIN
INSERT INTO jobs_posting_archive (job_id, job_name, description, posted_at, expires_at)
VALUES (:NEW.job_id, :NEW.job_name, :NEW.description, :NEW.posted_at, :NEW.expires_at);
END;
/

-- testing again
INSERT INTO vacant_jobs (job_name, description, expires_at, isActive)
VALUES ('Cleanup Test', 'confirm delete works with no FK issues', SYSTIMESTAMP + 1/1440, 'Y');
INSERT INTO vacant_jobs (job_name, description, expires_at, isActive)
VALUES ('Full Flow Test', 'Testing insert, notification, expiry, archive and delete together', SYSTIMESTAMP + 1/1440, 'Y');
COMMIT;

SELECT * FROM NOTIFICATIONS;
SELECT * FROM VACANT_JOBS;
SELECT * FROM JOBS_POSTING_ARCHIVE;

-- implicit cursor to change the description row by row
CREATE OR REPLACE PROCEDURE descriptions_lowercase_by_row AS
BEGIN
FOR job IN (SELECT job_id, description FROM vacant_jobs) LOOP
UPDATE vacant_jobs
SET description = to_lowercase(job.description)
WHERE job_id = job.job_id;
END LOOP;

COMMIT;
END descriptions_lowercase_by_row;
/

-- job to run the implicit cursor every 24 hours
BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME        => 'DESCRIPTION_TO_LOWER_BY_ROW_JOB',
    JOB_TYPE        => 'PLSQL_BLOCK',
    JOB_ACTION      => 'BEGIN descriptions_lowercase_by_row; END;',
    REPEAT_INTERVAL => 'FREQ=HOURLY; INTERVAL=24',
    START_DATE      => systimestamp,
    ENABLED         => TRUE
  );
END;
/

--TESTING
SELECT * FROM NOTIFICATIONS;

-- ===========================================================================
--PART: D

-- PROCEDURE TO INSERT INTO NOTIFICATIONS TABLE IF AN APPLICATION IS RECIEVED
CREATE OR REPLACE PROCEDURE application_notification (p_job_id IN NUMBER, p_applicant_email IN VARCHAR2)
AS
  v_job_name    VARCHAR2(150);
  v_description VARCHAR2(4000);
BEGIN
SELECT job_name, description INTO v_job_name, v_description
FROM vacant_jobs
WHERE job_id = p_job_id;

INSERT INTO notifications (type, message, job_id)
VALUES ('application', '[' || v_job_name || '] ' || p_applicant_email || ' applied', p_job_id);
END application_notification;
/

-- trigger that causes any insert into job_applications table to be inserted into the notifications table
CREATE OR REPLACE TRIGGER application_notification_trigger
AFTER INSERT ON job_applications
FOR EACH ROW
BEGIN
  application_notification(:NEW.job_id, :NEW.applicant_email);
END application_notification_trigger;
/

--TESTING
INSERT INTO job_applications (applicant_email, job_id)
VALUES ('test@test.com', (SELECT job_id FROM vacant_jobs WHERE job_name = 'Backend Developer'));
COMMIT;


-- IMPLICIT CURSOR TO KEEP ONLY THE LASTEST NOTIFICATION AND TAKE THE COUNT OF JOB APPLICANTS
CREATE OR REPLACE PROCEDURE minutely_notification_roundup AS
BEGIN
FOR job IN (SELECT job_id FROM vacant_jobs) LOOP

DELETE FROM notifications WHERE job_id = job.job_id
                            AND notification_id < (SELECT MAX(notification_id) FROM notifications WHERE job_id = job.job_id);

UPDATE notifications SET number_of_applicants = (SELECT COUNT(*) FROM job_applications WHERE job_id = job.job_id)
WHERE job_id = job.job_id;

END LOOP;

COMMIT;
END minutely_notification_roundup;
/

-- JOB TO CALL THE CURSOR EVERY 24 HOURS
BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME        => 'DAILY_NOTIFICATION_REDUCTION_AND_APPLICANT_COUNT_JOB',
    JOB_TYPE        => 'PLSQL_BLOCK',
    JOB_ACTION      => 'BEGIN minutely_notification_roundup; END;',
    REPEAT_INTERVAL => 'FREQ=HOURLY; INTERVAL=24',
    START_DATE      => systimestamp,
    ENABLED         => TRUE
  );
END;
/

-- TESTING
SELECT * FROM NOTIFICATIONS;
INSERT INTO job_applications (applicant_email, job_id)
VALUES ('a@test.com', (SELECT job_id FROM vacant_jobs WHERE job_name = 'Backend Developer'));
INSERT INTO job_applications (applicant_email, job_id)
VALUES ('b@test.com', (SELECT job_id FROM vacant_jobs WHERE job_name = 'Backend Developer'));
INSERT INTO job_applications (applicant_email, job_id)
VALUES ('c@test.com', (SELECT job_id FROM vacant_jobs WHERE job_name = 'Backend Developer'));
COMMIT;
SELECT * FROM JOB_APPLICATIONS;

-- ===========================================================================
-- PART: E
-- adding another column to track which notifications have been sent to slack or not
ALTER TABLE notifications ADD sent_to_slack CHAR(1) DEFAULT 'N' NOT NULL
    CONSTRAINT ck_notifications_sent_to_slack CHECK (sent_to_slack IN ('Y','N'));

-- explicit cursor to make the attributes available
CREATE OR REPLACE PROCEDURE get_pending_notifications (
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
OPEN p_cursor FOR
SELECT notification_id, type, message, created_at,
       number_of_applicants, job_id
FROM notifications
WHERE sent_to_slack = 'N'
ORDER BY created_at;
END get_pending_notifications;
/

-- procedure to set the sent_to_slack form 'N' TO 'Y'
CREATE OR REPLACE PROCEDURE mark_notification_sent (
  p_notification_id IN NUMBER
) AS
BEGIN
UPDATE notifications
SET sent_to_slack = 'Y'
WHERE notification_id = p_notification_id;
COMMIT;
END mark_notification_sent;
/

--TO GET THE PENDING NOTIFICATION EVERY SECOND
BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME        => 'CHECK_PENDING_NOTIFICATIONS_JOB',
    JOB_TYPE        => 'PLSQL_BLOCK',
    JOB_ACTION      => 'BEGIN get_pending_notifications; END;',
    REPEAT_INTERVAL => 'FREQ=SECONDLY; INTERVAL=1',
    START_DATE      => systimestamp,
    ENABLED         => TRUE
  );
END;
/

-- testing
INSERT INTO notifications (type, message, job_id)
VALUES ('new post', 'auto test 8', 1);
COMMIT;

select * from notifications;